runtime: python
env: flex
entrypoint: gunicorn -b :$PORT --worker-class eventlet -w 1 app:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

handlers:
  # Serve all static files with urls ending with a file extension
- url: /(.*\..+)$ 
  static_files: dist/\1
  upload: dist/(.*\..+)$
  # catch all handler to index.html
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  
network:
  session_affinity: true